name: Publish

on: push

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Publish to PyPI
      uses: casperdcl/deploy-pypi@v2
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        pip: wheel -w dist/ --no-deps .
        # only upload if a tag is pushed (otherwise just build & check)
        upload: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
